name: Generate categories

on:
    workflow_run:
        workflows: ["Deduplicate articles"]
        types:
            - completed
    workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Install python dependencies
        uses: actions/setup-python@v5
        with:
            python-version: 3.9
            cache: pip
      - name: Install libraries
        run: pip3 install -r ./prompting/requirements.txt
      - name: Run the category generation
        env:
            DATABASE_CONNECTION: ${{ secrets.DATABASE_CONNECTION }}
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
            python3 ./prompting/templates/category_generator.py
