name: RAG Risk Generation

on:
    workflow_dispatch:

jobs:
  deduplicate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Install python dependencies
        uses: actions/setup-python@v5
        with:
            python-version: 3.9
            cache: pip
      - name: Install libraries
        run: pip3 install -r ./rag/requirements.txt
      - name: Run the RAG risk generation
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 ./rag/rag.py
