name: Scrape latest data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install python dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: pip
      - name: Install libraries
        run: pip3 install -r ./scraping/requirements.txt
      - name: Run the scraper
        env:
          DATABASE_CONNECTION: ${{ secrets.DATABASE_CONNECTION }}
        run: |
          python3 ./scraping/gCaptain.py
          python3 ./scraping/loadstar.py
          python3 ./scraping/maritime_executive.py
          python3 ./scraping/tradewinds_spider.py
          python3 ./scraping/vesselfinder_spider.py